exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('birds').del()
    .then(function () {
      // Inserts seed entries
      return knex('birds').insert([
        { bird_id: 1, name: 'Tui', info: 'Tui are unique to New Zealand and belong to the honey-eater family which means that they feed mainly on nectar from the flowers of native plants. They can be quite aggressive! They will chase other Tui away from food and tasty nectar. Tui are found throughout the North, South and Stewart Islands of New Zealand.', image: '/images/tui.jpg', found: false, category: 'notThreatened', status: 'Not Threatened' },
        { bird_id: 2, name: 'Kererū', info: 'These big birds like to eat fruit, leaves, twigs and shoots and can eat so much that they get too full and fall out of trees. They are very important to our forests as they are the only bird left big enough to swallow seeds. They then poo the seeds out later in another place - helping to establish new forests. These birds are found all over New Zealand including many offshore islands.', image: '/images/kereru.jpg', found: false, category: 'notThreatened', status: 'Not Threatened' },
        { bird_id: 3, name: 'Pīwakawaka', info: 'Spot these friendly birds by their large tail. Also known as fantail, these birds build their nests with small materials woven with cobwebs and like to eat moths, flies, beetles and spiders. They also love to have a bird-bath! They live all over New Zealand, even in the Chatham Islands. You can find them in native and introduced forest, farm shelterbelts, orchards as well as suburban parks and gardens.', image: '/images/piwakawaka.jpg', found: false, category: 'notThreatened', status: 'Not Threatened' },
        { bird_id: 4, name: 'Ruru', info: 'Ruru are heard at dusk and throughout the night and they are named after their haunting call. Ruru can turn their heads 270 degrees and like to eat beetles, weta, moths and spiders. They are also known to eat small birds, rats and mice! Ruru are found throughout New Zealand and in Maori tradition they are seen as watchful guardians of the forest.', image: '/images/ruru.jpg', found: false, category: 'notThreatened', status: 'Not Threatened' },
        { bird_id: 5, name: 'Kōtare', info: 'Kōtare, also known as sacred kingfisher, are the only species of kingfisher native to New Zealand. They like to build perches in earth banks, which they tunnel into with their beaks. They live both around the sea, where they feed on small crabs and fish, as well as inland, where what they feed on includes worms, weta, spiders, mice and even small birds!', image: '/images/kotare.jpg', found: false, category: 'notThreatened', status: 'Not Threatened' },
        { bird_id: 6, name: 'Tōrea Pango', info: 'Tōrea Pango, also known as variable oystercatcher, are found on shorelines around New Zealand. They are usually found in pairs and can be seen searching for shellfish. They really like sandy dunes and you don’t usually see them too far from the coast, where they eat mussels, tuatua and cockles along with other shellfish.', image: '/images/toreapango.jpg', found: false, category: 'atRisk', status: 'Recovering' },
        { bird_id: 7, name: 'Kakīānau', info: 'Kakīānau, also known as black swan, are native to New Zealand. They became extinct after the first human settlement of New Zealand but were reintroduced from Australia in the 1860s. They live throughout New Zealand and live on larger lakes and estuaries. They are herbivores and like to eat freshwater plants and Zostera.', image: '/images/kakianau.jpg', found: false, category: 'notThreatened', status: 'Not Threatened' },
        { bird_id: 8, name: 'Rosella', info: 'Rosella were introduced from Australia and you can usually hear them coming with their noisy chatter and alarm calls. They have bright red heads and white on their cheeks. They are mainly found in Northland, Auckland, Waikato, Wairarapa and Wellington and can be found in urban parks as well as rural areas. They like to eat seeds as well as fruit and leaves.', image: '/images/rosella.jpg', found: false, category: 'notThreatened', status: 'Introduced and Naturalised' },
        { bird_id: 9, name: 'Quail', info: 'Quail like to eat seeds, fruit and leaves. They feed mainly in the early morning and late afternoon and love to eat seeds spilled from bird feeders - beware of scaring them off though, they are very shy! They are found throughout most of New Zealand on the scrubby edges of rivers, forests, roads and rural gardens.', image: '/images/californiaquail.jpg', found: false, category: 'notThreatened', status: 'Introduced and Naturalised' },
        { bird_id: 10, name: 'Thrush', info: 'Thrush like to usually eat from the ground, feeding on spiders, snails, slugs and worms but they also like to eat small berries. They can break open a snail by smashing the shell on a hard surface. They live all over New Zealand up until around 800m above sea level. You can find them in your backyard as well as lowland native forest.', image: '/images/thrush.jpg', found: false, category: 'notThreatened', status: 'Introduced and Naturalised' },
        { bird_id: 11, name: 'Kakapo', info: 'The Kakapo is the only parrot which cannot fly. It lived in grassland, scrubland and coastal regions of New Zealand, but is now so rare they can only be seen on protected offshore islands. Kakapo means night parrot.Kakapos are most active at night (nocturnal), and like to be alone. To keep other kakapos out of their territory, they make a skraaarking sound. The Kakapo can live for about 60 years.', image: '/images/kakapo.jpg', found: false, category: 'threatened', status: 'Nationally Critical' },
        { bird_id: 12, name: 'Kea', info: 'The kea is a parrot and like all parrots it has 4 toes on each foot – two that point forward and two that point backward (zygodactyl). This allows it to easily manipulate objects (more like having hands than feet), and move around in the trees and on the ground. You wouldn’t know it to look at a a kea but the orange feathers can also be seen in the UV spectrum – light waves that we humans cant see in but many birds and insects can. Other colours on the kea include a beautiful royal blue on the top surface of each wings long flight feathers and red/orange on the rump (tail) feathers.', image: '/images/kea.JPG', found: false, category: 'threatened', status: 'Nationally Endangered' },
        { bird_id: 13, name: 'Takahe', info: 'The Takahē is a flightless bird indigenous to New Zealand and belonging to the rail family. It was thought to be extinct after the last four known specimens were taken in 1898. However, after a carefully planned search effort the bird was rediscovered by Geoffrey Orbell near Lake Te Anau in the Murchison Mountains, South Island, on November 20, 1948.', image: '/images/takahe.jpg', found: false, category: 'threatened', status: 'Nationally Vulnerable' },
        { bird_id: 14, name: 'Banded Rail', info: 'Banded rail are rarely seen, as they are well-camouflaged and remain under the cover of wetland vegetation, although their footprints are often seen. They are now mainly found in mangrove and saltmarsh vegetation in the upper North Island. They have disappeared from most of New Zealand since the 1970s, but remain in coastal wetlands in the upper North Island, Marlborough and Nelson, in rush-covered areas and coastal wetlands on Great Barrier Island and in forest and shrubland on the Three Kings Islands and on four islands off Stewart Island.', image: '/images/bandedrail.JPG', found: false, category: 'atRisk', status: 'Declining' },
        { bird_id: 15, name: 'Fairy Prion', info: 'The fairy prion is an abundant and familiar petrel of exposed coastal waters around New Zealand, especially from Cook Strait southwards. It often feeds in large flocks over tide rips near offshore rocks and islands. Slightly smaller than a red-billed gull, fairy prions are very similar in appearance to the five other prion species: blue-grey and black above, and white below, with blue bill and legs. This colouration and their habit of flying along wave troughs make prions difficult to follow with binoculars from a moving boat deck. The Poor Knights Islands are the only northern breeding site, but fairy prions breed in burrows and rock crevices on many islands from Cook Strait south, including on the Chatham Islands and several subantarctic island groups. The largest colony holds an estimated 1.8 million pairs. Fairy prions, along with other prion species, are often found storm-wrecked on beaches exposed to the open ocean, especially on the west coast of both main islands.', image: '/images/fairyprion.jpg', found: false, category: 'atRisk', status: 'Relict' },
        { bird_id: 16, name: 'Black Shag', info: 'This large, mainly black shag is often seen individually or in small groups roosting on rocky headlands, in trees or on artificial structures. It usually forages alone. Even though readily seen about harbours and estuaries associated with cities or towns, black shags are wary of close approach by people, probably as a result of persecution by fishers and waterfowl hunters.', image: '/images/blackshag.JPG', found: false, category: 'atRisk', status: 'Naturally Uncommon' }
      ])
    })
}
